# Generated by Django 4.1.5 on 2023-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
